---
title: "Grid search optimization for GPP Runout distance model"
author: "Jason Goetz"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
 %\VignetteIndexEntry{Runout grid search optimization}
 %\VignetteEngine{knitr::rmarkdown}
 %\VignetteEncoding{UTF-8}
 \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
comment = "#>")
knitr::opts_knit$set(root.dir = "/home/jason/Data/Chile/")
```

# Load packages and data

```{r}
library(raster)
library(rgdal)
library(Rsagacmd)

dem <- raster("dem_alos_12_5m _no sinks.tif")

# slide start/source points
runout_points <- readOGR(".", "dflow_points_v1_reposition")

# actual/mapped debris flow runout tracks
runout_polygons <- readOGR(".", "dflow_polygons_v1_reposition_sample_100")

# make sure CRS is assigned
crs(runout_points) <- crs(runout_polygons)


# assign an id by row
runout_polygons$objectid <- 1:100
```

# Initiate a SAGA-GIS geoprocessor object

```{r}
saga <- saga_gis()
```

# Runout path performance

```{r}
library(runout.opt)

rwPerformance(dem, slide_plys = runout_polygons, source_pnts = runout_points,
                   slide_id = 2, slp = 33, ex = 3, per = 2,
                   gpp_iter = 1000, buffer_ext = 500, buffer_source = 50,
                   plot_eval = TRUE)
```

# Grid search for optimal performance

```{r}
# Set up grid search space
steps <- 3
rwexp_vec <- seq(1.3, 3, len=steps)
rwper_vec <- seq(1.5, 2, len=steps)
rwslp_vec <- seq(20, 40, len=steps)

workspace_dir <- "/home/jason/Scratch/F_Testing"

rw_gridsearch <- rwGridsearch(dem, workspace = workspace_dir, slide_plys = runout_polygons, source_pnts = runout_points,
               slide_id = 2, slp_v = rwslp_vec, ex_v = rwexp_vec, per_v = rwper_vec,
               gpp_iter = 1000, buffer_ext = 500, buffer_source = 50,
               plot_eval = FALSE)

rw_gridsearch
```
